version: '2'

services:

  php:
    restart: always
    build: docker/phpfpm
    image: phpfpm/latest
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    links:
      - db:db

  web:
    restart: always
    image: nginx:1.12.1-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php:php

  db:
    restart: always
    image: mariadb:10.1.25
    ports:
      - "3306:3306"
    volumes:
      - ./docker/databases:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
