#!/usr/bin/env ruby

Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.3"

    config.vm.network "private_network", ip: "192.168.79.79"
    config.vm.synced_folder "../", "/srv", mount_options: ["dmode=777,fmode=666"]

    config.vm.provider :virtualbox do |v|
      v.name = "vagrant_centos_with_shell_provision"
      v.memory = "256"
    end

    config.vm.provision :shell, path: "./shell/yum.sh"
    config.vm.provision :shell, path: "./shell/firewall.sh"
    config.vm.provision :shell, path: "./shell/mariadb.sh"
    config.vm.provision :shell, path: "./shell/nginx.sh"
    config.vm.provision :shell, path: "./shell/redis.sh"
    config.vm.provision :shell, path: "./shell/php.sh"
end
